#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  Oct 22, 2021 03:14:20 PM -03  platform: Windows NT
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background #486855 
    wm focusmodel $top passive
    wm geometry $top 600x450+463+227
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 4330 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    frame $top.fra58 \
        -borderwidth 2 -background #0000ff -height 305 -width 455 
    vTcl:DefineAlias "$top.fra58" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra58
    label $site_3_0.lab59 \
        -background #0000ff -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 20 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground #ffffff -text Login 
    vTcl:DefineAlias "$site_3_0.lab59" "Label1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent60 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 194 
    vTcl:DefineAlias "$site_3_0.ent60" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent61 \
        -background white -disabledforeground #a3a3a3 -font TkFixedFont \
        -foreground $vTcl(actual_gui_fg) -insertbackground black -width 194 
    vTcl:DefineAlias "$site_3_0.ent61" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab62 \
        -activebackground #f9f9f9 -activeforeground black -background #0000ff \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 17 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text Usuario 
    vTcl:DefineAlias "$site_3_0.lab62" "Label1_1" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab63 \
        -activebackground #f9f9f9 -activeforeground black -background #0000ff \
        -disabledforeground #a3a3a3 \
        -font "-family {Segoe UI} -size 17 -weight normal -slant roman -underline 0 -overstrike 0" \
        -foreground #ffffff -highlightbackground $vTcl(actual_gui_bg) \
        -highlightcolor black -text Senha 
    vTcl:DefineAlias "$site_3_0.lab63" "Label1_2" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but64 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #00ffff -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Logar 
    vTcl:DefineAlias "$site_3_0.but64" "Button1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but65 \
        -activebackground $vTcl(analog_color_m) -activeforeground #000000 \
        -background #00ffff -disabledforeground #a3a3a3 \
        -foreground $vTcl(actual_gui_fg) \
        -highlightbackground $vTcl(actual_gui_bg) -highlightcolor black \
        -pady 0 -text Cadastrar 
    vTcl:DefineAlias "$site_3_0.but65" "Button1_1" vTcl:WidgetProc "Toplevel1" 1
    ttk::separator $site_3_0.tSe66 \
        -orient vertical 
    vTcl:DefineAlias "$site_3_0.tSe66" "TSeparator1" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab59 \
        -in $site_3_0 -x 0 -relx 0.352 -y 0 -rely 0.033 -width 0 \
        -relwidth 0.251 -height 0 -relheight 0.138 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent60 \
        -in $site_3_0 -x 0 -relx 0.066 -y 0 -rely 0.328 -width 194 \
        -relwidth 0 -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent61 \
        -in $site_3_0 -x 0 -relx 0.066 -y 0 -rely 0.59 -width 194 -relwidth 0 \
        -height 20 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 0 -relx 0.022 -y 0 -rely 0.164 -width 0 \
        -relwidth 0.273 -height 0 -relheight 0.138 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 0 -relx 0.022 -y 0 -rely 0.426 -width 0 \
        -relwidth 0.251 -height 0 -relheight 0.138 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but64 \
        -in $site_3_0 -x 0 -relx 0.11 -y 0 -rely 0.721 -width 137 -relwidth 0 \
        -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but65 \
        -in $site_3_0 -x 0 -relx 0.505 -y 0 -rely 0.721 -width 147 \
        -relwidth 0 -height 44 -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tSe66 \
        -in $site_3_0 -x 0 -relx 0.464 -y 0 -rely 0.731 -width 0 \
        -relwidth 0.004 -height 0 -relheight 0.134 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra58 \
        -in $top -x 0 -relx 0.133 -y 0 -rely 0.111 -width 0 -relwidth 0.758 \
        -height 0 -relheight 0.678 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

